import { GetStaticProps } from "next";
import Head from "next/head";

import { Header } from "../components";
import { WiktionarySection } from "../components/WiktionarySection";

import { lookup } from "./api/lookup";

interface HomeProps {
  html: string;
}

export default function Home({ html = "" }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header></Header>
        <h1>Wiktionary Reader</h1>
        <WiktionarySection
          html={html}
        />
      </main>

      {/* <Footer /> */}
    </>
  );
}


export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const { html } = await lookup({
    language: "Latin",
    word: "scio"
  });

  return {
    props: {
      html,
    },
  };
};