import { GetStaticProps } from "next";
import Head from "next/head";

import { Header } from "../components";
import { WiktionarySection } from "../components/WiktionarySection";

import { lookup, LookupResponse } from "./api/lookup";

export default function Home({ html, language, word }: LookupResponse) {
  return (
    <>
      <Head>
        <title>Wiktionary Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header language={language} word={word} />

        <div className="flex-col center">
          <h1>{word}</h1>
          <span className="text-2xl">{language}</span>
        </div>

        <WiktionarySection html={html} />
      </main>

      {/* <Footer /> */}
    </>
  );
}


export const getStaticProps: GetStaticProps<LookupResponse> = async () => {
  const { language, word, html } = await lookup({
    language: "Latin",
    word: "scio"
  });

  return {
    props: {
      html,
      language,
      word
    },
  };
};