import Head from "next/head";

import { Header } from "../components";
import { WiktionarySection } from "../components/WiktionarySection";

import { isISO6391LanguageCode, LanguageCode } from "../lib/language";
import { LookupResponse } from "./api/lookup";

import ISO6391 from "iso-639-1";
import { useRouter } from "next/router";
import useSWR from "swr";

export default function Home() {
  const { query } = useRouter();
  let language: LanguageCode;
  let word: string;

  if (typeof query.word === "string") {
    word = query.word;
  } else {
    word = "hello";
  }

  if (
    typeof query.language === "string" &&
    isISO6391LanguageCode(query.language)
  ) {
    language = query.language;
  } else {
    language = "en";
  }

  const { data } = useSWR<LookupResponse>(
    `/api/lookup?word=${word}&language=${language}`,
    async (url: string) => (await fetch(url)).json(),
  );

  if (!data) {
    return null;
  }

  const { error, html } = data;
  const languageName = ISO6391.getName(language);

  return (
    <>
      <Head>
        <title>Wiktionary Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header language={language} word={word} />

        <div className="flex-col center">
          <h1>
            {word}
          </h1>
          <span className="text-2xl">
            {languageName}
          </span>
        </div>

        {
          error
            ? (
              <code>{JSON.stringify(error)}</code>
            )
            : (
              <WiktionarySection html={html} />
            )
        }
      </main>

      {/* <Footer /> */}
    </>
  );
}


// export const getStaticProps: GetStaticProps<LookupResponse> = async () => {
//   const args: LookupRequest = {
//     language: "la",
//     word: "scio"
//   };

//   const { language, word, html } = await lookup(args);

//   return {
//     props: {
//       html,
//       language,
//       word
//     },
//   };
// };